name: built

on:
  push:
  pull_request:

jobs:
  build:
    name: node@${{ matrix.node }}

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ["12.x", "14.x", "16.x"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn build
